### ISSUE TITLE
Failure to Download anything

### ISSUE THREAD

**Issue by QueenAng** [EchterAlsFake/Porn_Fetch#59]
Issue downloading anything. on the GUI Version it works individually but an entire account crashes after some videos. om the CMD Version, It fails to do any video. it hits 100% and then shows this:

Exception in thread Thread-1 (download):
Traceback (most recent call last):
  File "threading.py", line 1045, in _bootstrap_inner
  File "threading.py", line 982, in run
  File "Porn_Fetch_CLI.py", line 433, in download
  File "ffmpeg_progress_yield\ffmpeg_progress_yield.py", line 198, in run_command_with_progress
  File "subprocess.py", line 1026, in __init__
  File "subprocess.py", line 1462, in _execute_child
  File "subprocess.py", line 608, in list2cmdline
  File "<frozen os>", line 824, in fsdecode
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by EchterAlsFake** [comment]
Hi, 

I just tried it out using both the CLI from the master branch and the Porn Fetch v3.4 CLI and I did not have any problems. I assume you are using ffmpeg as the threading mode. Unfortunately I am not able to reproduce this issue, but it seems as if it would be an issue with the path and not with the downloading itself. 

It would be very helpful for me if you could share the path where you configured Porn Fetch to save videos to. You can of course strip out sensitive information like your username. I would also need an example video where this happens.

The other issue you mentioned in the GUI version where it fails after some videos... You said it "crashes". Do you mean the application itself crashes, like the window is closing or does a download crash / fail and if yes, does it show any errors?

Thanks for reporting :)

**Comment by EchterAlsFake** [comment]
Okay, so you used an older version then and now with 3.4 it worked with ffmpeg right? 

So the issues with that path can be caused by quite a lot. Maybe it's me just writing stupid code again (wouldn't be the first time), but in the background of Porn Fetch there are actually a lot of side projects involved and it's hard to maintain and keep them consistent. So I experimented with switching to `os.path.join` in Python instead of raw strings. So basically this will improve the output path and maybe fix that issue. But I can't just implement all that right now, because it's very time consuming, so I have to notify you again when Version 3.5 is ready. Probably in 3-4 weeks, I can't promise anything.

The issues with downloading is also a deep topic. PornHub has mechanisms to detect bots and although I and Egsagon did a lot to get around that, sometimes it just fails, and I need to do a deep stress test to harden Porn Fetch against such issues. 

So but I still need to ask you what exactly you mean with "closing"

Thanks for your reply :)

**Comment by QueenAng** [comment]
Yes after the update i was able to successfully download. As for the closing, like I said it simply closes. the Command Prompt and the UI both Stop and close.

**Comment by EchterAlsFake** [comment]
Okay thanks for the clarification!

I try to solve that issue with the UI closing
