### ISSUE TITLE
Turn on flashback

### ISSUE THREAD

**Issue by matcha6666** [EchterAlsFake/Porn_Fetch#8]
Windows 2.8 version failed to open and crashed

**Comment by matcha6666** [comment]
: DEBUG :  : MSG : Starting Porn Fetch main widget
 : DEBUG :  : MSG : Loaded Icons
Traceback (most recent call last):
  File "Porn_Fetch.py", line 1077, in <module>
  File "Porn_Fetch.py", line 1031, in main
  File "Porn_Fetch.py", line 161, in check_license_and_proceed
  File "Porn_Fetch.py", line 187, in show_main_window
  File "Porn_Fetch.py", line 341, in __init__
  File "Porn_Fetch.py", line 922, in load_user_settings
  File "configparser.py", line 1273, in __getitem__
KeyError: 'search_limit'
[29912] Failed to execute script 'Porn_Fetch' due to unhandled exception!

**Comment by EchterAlsFake** [comment]
You need to delete the file "config.ini"

You probably downloaded Porn Fetch to the exact same place then it was on v2.7 and that's why the old config is used.  When you delete it, the new configuration file will automatically be created :)

**Comment by matcha6666** [comment]
Oh, problem solved, thanks
